<!-- 

<div class="field platform_code">
    <label class="label" for="platform_code">

      <span><?= $block->escapeHtml(__('Platform Code')) ?>   </span>
    </label>
    <div class="control">
       <input type="text" name="platform_code" id="platform_code"  data-form-part="platform_code"  value="" title="<?= $block->escapeHtmlAttr(__('Platform Code')) ?>" class="input-text" data-validate="{required:false}">
    </div>
</div> -->
